import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://xkcd.com/info.0.json`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
  


export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>xkcd Daily Comic Strip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          xkcd Daily Comic Strip
        </h1>

          {console.log(data)}
        <ul className={styles.grid}>
        
            <li key="id" className={styles.card}>
              <a href="">
                <Image width="740" height="360" src={data.img} alt=""/>
                <p style={{fontSize: 10, textAlign: 'center'}}>Date: {("0" + data.month).slice(-2)}-{("0" + data.day).slice(-2)}-{data.year}</p>
                <p style={{fontSize: 10, textAlign: 'center'}}>Comic №: {data.num}</p>
                <br/>
                <p style={{fontSize: 14, textAlign: 'center'}}>{data.alt}</p>
              </a>
            </li>
          
          

        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
