import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  //try...catch statement to handle errors
  try{
    // Fetch data from API
    const res = await fetch(`https://xkcd.com/info.0.json`)
    const data = await res.json()
    // Pass data to the page via props
    return { props: { data } }
  }
  catch(err){
    console.log(err)
  }

}
  


export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>xkcd Daily Comic Strip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          xkcd Daily Update
        </h1>
          {console.log(data)}

          <ul className={styles.grid}>
        
            <li key="id" className={styles.card}>
              <a href="https://xkcd.com/archive/">
                
                {/* check if image available with ternary operator */}
                {data.img ? <Image src={data.img} width="100%" height="100%" layout="responsive" objectFit="contain" alt=""/> : <Image src='https://u.cubeupload.com/avi2022/noimage.png' width="100%" height="100%" layout="responsive" objectFit="contain" alt=""/>}
                
                <p style={{fontSize: 10, textAlign: 'center'}}>Date: {("0" + data.month).slice(-2)}-{("0" + data.day).slice(-2)}-{data.year}</p>
                <p style={{fontSize: 10, textAlign: 'center'}}>Comic №: {data.num}</p>
                <br/>
                <p style={{fontSize: 14, textAlign: 'center'}}>{data.alt}</p>
              </a>
            </li>
          

        </ul>
      </main>

      <footer className={styles.footer}>
          <a href='https://xkcd.com/'>
          <small>For more visit xkcd.com</small>
          </a>
      </footer>
    </div>
  )
}
